#################################
# Plugin Configuration File     #
# @author MlgmXyysd             #
# @create 2018/07/09 10:12      #
# @lastupdate 2018/07/09 10:12  #
# Copyright (C) 2018 Server CT  #
# All Rights Reserved.          #
#################################

isSentConsoleMsg: false